language: java

jdk:
  - oraclejdk8

env:
  global:
    - CODACY_PROJECT_TOKEN=9c6144da20d44fd28bd84e0b204680d5

sudo: required

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue

after_success:
  - ./gradlew test jacocoTestReport coveralls